In [6]:
import numpy as np
from numpy.linalg import eig
from numpy.polynomial import Polynomial

# Given polynomial coefficients (assuming the leading coefficient is 1)
coefficients = [1]  # This represents x^n where n is the degree of the polynomial
coefficients.extend([-a for a in [1.2, -3.4, 5.6, -7.8]])  # Example coefficients for a_0, a_1, ..., a_{n-1}

# Construct the companion matrix
def construct_companion_matrix(coeffs):
    n = len(coeffs) - 1  # Degree of the polynomial
    companion_matrix = np.zeros((n, n))
    companion_matrix[:, -1] = -np.array(coeffs[:-1])  # Set last column to negative coefficients
    companion_matrix[1:, :-1] = np.eye(n - 1)  # Set sub-diagonal to 1's
    return companion_matrix

companion_matrix = construct_companion_matrix(coefficients)
print("Companion Matrix:")
print(companion_matrix)

# Verify that the characteristic polynomial is p(x)
p = Polynomial(coefficients)
characteristic_polynomial = np.poly(companion_matrix)
print("\nCharacteristic Polynomial Coefficients:")
print(characteristic_polynomial)
print("\nOriginal Polynomial Coefficients:")
print(p.coef)

# Check if the polynomials are the same (within a tolerance due to floating-point arithmetic)
print("\nAre the polynomials equivalent (within tolerance)?")
print(np.allclose(characteristic_polynomial, p.coef[::-1]))  # Reverse the coefficients of p for comparison


Companion Matrix:
[[ 0.   0.   0.  -1. ]
 [ 1.   0.   0.   1.2]
 [ 0.   1.   0.  -3.4]
 [ 0.   0.   1.   5.6]]

Characteristic Polynomial Coefficients:
[ 1.  -5.6  3.4 -1.2  1. ]

Original Polynomial Coefficients:
[ 1.  -1.2  3.4 -5.6  7.8]

Are the polynomials equivalent (within tolerance)?
False


In [7]:
# Wilkinson's polynomial coefficients can be computed as follows:
wilkinson_coeffs = np.poly(np.arange(1, 16))[::-1]

# Construct the companion matrix for Wilkinson's polynomial
companion_matrix_wilkinson = construct_companion_matrix(wilkinson_coeffs)

# Find eigenvalues of the companion matrix (which are the roots of the polynomial)
eigenvalues = eig(companion_matrix_wilkinson)[0]

# Find roots using the built-in method
roots = np.roots(wilkinson_coeffs)

# Calculate relative errors
def relative_error(true_values, approx_values):
    return np.abs((true_values - approx_values) / true_values)

relative_errors_eig = relative_error(np.arange(1, 16), np.sort(eigenvalues))
relative_errors_roots = relative_error(np.arange(1, 16), np.sort(roots))

print("Roots found using the companion matrix method:")
print(np.sort(eigenvalues))
print("\nRelative Error using the companion matrix method:")
print(relative_errors_eig)

print("\nRoots found using the built-in roots() method:")
print(np.sort(roots))
print("\nRelative Error using the built-in roots() method:")
print(relative_errors_roots)


Roots found using the companion matrix method:
[ 1.          2.          3.          4.          5.00000002  5.99999986
  7.0000005   7.99999905  9.00000056 10.00000169 10.9999952  12.00000592
 12.99999592 14.00000153 14.99999976]

Relative Error using the companion matrix method:
[2.52242671e-13 7.20867810e-12 3.75270185e-11 3.03929992e-10
 4.42740795e-09 2.37966331e-08 7.12590539e-08 1.18531835e-07
 6.24738580e-08 1.68503832e-07 4.36500276e-07 4.93656322e-07
 3.14089011e-07 1.09101723e-07 1.61696518e-08]

Roots found using the built-in roots() method:
[0.06666666 0.07142864 0.07692283 0.08333383 0.09090843 0.10000061
 0.11111069 0.12500022 0.14285705 0.1666667  0.19999999 0.25
 0.33333333 0.5        1.        ]

Relative Error using the built-in roots() method:
[0.93333334 0.96428568 0.97435906 0.97916654 0.98181831 0.98333323
 0.98412704 0.98437497 0.98412699 0.98333333 0.98181818 0.97916667
 0.97435897 0.96428571 0.93333333]


In [8]:
# Perturb Wilkinson's polynomial coefficients
wilkinson_coeffs_perturbed = wilkinson_coeffs.copy()
wilkinson_coeffs_perturbed[-2] -= 0.00001  # Change the coefficient of x^14

# Find roots of the perturbed polynomial
perturbed_roots = np.roots(wilkinson_coeffs_perturbed)

print("Roots of the perturbed Wilkinson's polynomial:")
print(perturbed_roots)

# Compare with unperturbed roots
print("\nChanges in roots due to perturbation:")
print(perturbed_roots - roots)


Roots of the perturbed Wilkinson's polynomial:
[1.        +0.j         0.5       +0.j         0.33333333+0.j
 0.2500007 +0.j         0.19997189+0.j         0.16714406+0.j
 0.13772802+0.00571198j 0.13772802-0.00571198j 0.10936515+0.01645399j
 0.10936515-0.01645399j 0.08559827+0.01613955j 0.08559827-0.01613955j
 0.06950079+0.00901614j 0.06950079-0.00901614j 0.06339456+0.j        ]

Changes in roots due to perturbation:
[ 4.44089210e-16+0.j          6.60116406e-12+0.j
 -5.54857310e-09+0.j          7.00465084e-07+0.j
 -2.81004761e-05+0.j          4.77364537e-04+0.j
 -5.12902888e-03+0.00571198j  1.27277984e-02-0.00571198j
 -1.74554234e-03+0.01645399j  9.36453654e-03-0.01645399j
 -5.31016294e-03+0.01613955j  2.26443476e-03-0.01613955j
 -7.42204445e-03+0.00901614j -1.92785503e-03-0.00901614j
 -3.27209510e-03+0.j        ]
