In [2]:
import numpy as np

In [3]:
def backward(U, b):
    # Check if matrix and vector sizes are compatible
    if U.shape[0] != U.shape[1] or U.shape[0] != b.shape[0]:
        raise ValueError("Incompatible sizes of matrix U and vector b.")
    
    n = len(b)
    x = np.zeros(n)
    
    for i in range(n-1, -1, -1):
        sum_val = sum([U[i][j] * x[j] for j in range(i+1, n)])
        x[i] = (b[i] - sum_val) / U[i][i]
    
    return x

U = np.array([[1, 2, 6, -1],
              [0, 3, 1, 0],
              [0, 0, 4, -1],
              [0, 0, 0, 2]])

b = np.array([-1, -3, -2, 4])
print(backward(U, b))


[ 3. -1.  0.  2.]


In [4]:
def backward_check(U, b):
    # Check if matrix and vector sizes are compatible
    if U.shape[0] != U.shape[1] or U.shape[0] != b.shape[0]:
        raise ValueError("Incompatible sizes of matrix U and vector b.")
        
    # if U is invertible 
    inverse_U = np.linalg.inv(U)
    
    x = np.dot(inverse_U, b)
    
    print(x)
  
U = np.array([[1, 2, 6, -1],
              [0, 3, 1, 0],
              [0, 0, 4, -1],
              [0, 0, 0, 2]])

b = np.array([-1, -3, -2, 4])
backward_check(U, b)

[ 3. -1.  0.  2.]


In [5]:
"""
check if backward(U, b) works
- Cross-verify the solution by substituting the solution x back into the equation Ux=b to see if it holds true.
- Compare the solution with numpy.linalg.solve.

"""

def check1(U, b):
    x = np.linalg.solve(U,b)

    print(x)

U = np.array([[1, 2, 6, -1],
              [0, 3, 1, 0],
              [0, 0, 4, -1],
              [0, 0, 0, 2]])

b = np.array([-1, -3, -2, 4])
check1(U, b)


def check2(U,x):
    b = np.dot(U, x)
    
    print(b)
    
U = np.array([[1, 2, 6, -1],
              [0, 3, 1, 0],
              [0, 0, 4, -1],
              [0, 0, 0, 2]])
x = np.array([3, -1, 0, 2])
check2(U,x)

[ 3. -1.  0.  2.]
[-1 -3 -2  4]


In [3]:
import numpy as np

def backward(U, b):
    # Check if matrix and vector sizes are compatible
    if U.shape[0] != U.shape[1] or U.shape[0] != b.shape[0]:
        raise ValueError("Incompatible sizes of matrix U and vector b.")
    
    n = len(b)
    x = np.zeros(n)
    
    for i in range(n-1, -1, -1):
        # Check for zero or near-zero diagonal elements
        if abs(U[i][i]) < 1e-10:
            raise ValueError("Diagonal element too close to zero, may cause division error.")
        
        sum_val = sum([U[i][j] * x[j] for j in range(i+1, n)])
        x[i] = (b[i] - sum_val) / U[i][i]
    
    return x

# Random matrix and vector
n = 100
U = np.triu(np.random.rand(n, n))
b = np.random.rand(n)

x = backward(U, b)

# Compute the error and relative error
error = np.linalg.norm(np.dot(U, x) - b)
relative_error = error / np.linalg.norm(b)
print("Error:", error)
print("Relative Error:", relative_error)

# Compare with built-in solver
x_np = np.linalg.solve(U, b)
print(abs(x-x_np))


Error: 112555.0275513178
Relative Error: 20227.92888933979
[2.13647360e+07 1.21896960e+07 2.39206400e+06 5.01350400e+06
 3.39968000e+05 4.21068800e+06 4.13696000e+05 5.14048000e+05
 3.56352000e+05 1.54880000e+04 2.96960000e+04 6.50240000e+04
 1.15200000e+04 1.24160000e+04 3.10000000e+02 4.14000000e+02
 4.84000000e+02 4.60000000e+01 1.04375000e+01 5.45312500e+00
 8.64062500e+00 2.29687500e+00 6.96875000e+00 2.40625000e+00
 3.12500000e+00 3.00000000e+00 2.73437500e-02 5.93750000e-01
 1.28125000e+00 2.81250000e-01 9.68750000e-01 1.09863281e-03
 3.12805176e-04 1.46484375e-03 2.44140625e-04 4.88281250e-04
 1.22070312e-04 3.05175781e-04 0.00000000e+00 3.81469727e-05
 0.00000000e+00 1.22070312e-04 3.24249268e-05 4.95910645e-05
 6.86645508e-05 1.29699707e-04 2.57492065e-05 2.67028809e-05
 9.15527344e-05 6.10351562e-05 1.43051147e-06 3.57627869e-07
 1.33514404e-05 7.62939453e-06 1.07288361e-06 2.23517418e-08
 1.34110451e-07 7.45058060e-08 7.07805157e-08 6.70552254e-08
 1.93715096e-07 1.04308128

In [ ]:
"""
The code does not solve the problem correctly. 
The 1st operation agrees with machine precision. 
But the errors keep accumulating and for the last rwo of A which receives (n-1) factors of the scaling factor, 
each of which introduce a rounding error from the multiplication. The errors get amplified enormously. 
"""